app/__init__.py
from flask import Flask
import os

STATIC_BASE_URL = 'https://static.abotkin.space'


def create_app():
    app = Flask(__name__,  static_folder=None)

    @app.context_processor
    def inject_static_url():
        return {'static_url': STATIC_BASE_URL}

    # Конфигурация
    app.config['UPLOAD_FOLDER'] = os.path.join(
        os.path.dirname(__file__), 'uploads')
    app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024

    # Создаем папку для загрузок
    os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)

    from .routes import bp
    app.register_blueprint(bp)

    return app

app/routes.py
from flask import Blueprint, render_template, request, current_app
from .utils.file_upload import FileUploader 

bp = Blueprint('main', __name__)
uploader = FileUploader()

@bp.route('/static/<path:filename>')
def block_static(filename):
    return "Not Found", 404

@bp.route('/')
def index():
    headers = dict(request.headers)
    return render_template('index.html', headers=headers)


@bp.route('/test')
def test():
    return render_template('test.html')


@bp.route("/about")
def about():
    return render_template("about.html")


@bp.route("/contact")
def contact():
    return render_template("contact.html")


@bp.route('/upload', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        if 'file' not in request.files:
            return render_template('upload.html', message='Файл не выбран')

        file = request.files['file']
        filename, error = uploader.save_file(
            file, current_app.config['UPLOAD_FOLDER'])

        if error:
            return render_template('upload.html', message=error)

        file_url = f"/uploads/{filename}"
        return render_template('upload.html',
                               message=f'Файл загружен: <a href="{file_url}">{filename}</a>')

    return render_template('upload.html')

app/templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block content %}
    <h1>About Us</h1>
    <p>This page tells you about our project.</p>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Flask App{% endblock %}</title>
    <link rel="stylesheet" href="{{ static_url }}/style.css">
</head>

<body>
    <nav>
        <a href="{{ url_for('main.index') }}">Home</a>
        <a href="{{ url_for('main.about') }}">About</a>
        <a href="{{ url_for('main.contact') }}">Contact</a>
        <a href="{{ url_for('main.upload_file') }}">Files</a>
    </nav>
    <div class="container">
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
    <div class="main-img"><img src="{{ static_url }}/img/eye.webp" alt=""></div>
</body>

</html>

app/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Contact Us</h1>
    <p>Email: example@example.com</p>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Welcome to the Home Page!</h1>
    <p>This is the main page of the application.</p>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome to the conspiracy theory home page!</h1>
<p>This is the main page of the application.</p>
<!-- <img src="../static/img/dollar.jpg" alt="" width="100" height="100"> -->
test
            {% for name, value in headers.items() %}
            <div class="http-headers">
		    <span class="http-headers-name">{{ name }}</span>
                <span class="http-headers-value">{{ value }}</span>
            </div>
            {% endfor %}
{% endblock %}

app/templates/test.html
{% extends "base.html" %}

{% block title %}Test{% endblock %}

{% block content %}
<h1>Welcome to the Test Page!</h1>
<p>This is the test page of the application.</p>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}

{% block title %}Загрузка файла{% endblock %}

{% block content %}
<h1>Загрузите файл</h1>
<form method="POST" enctype="multipart/form-data">
    <input type="file" name="file">
    <input type="submit" value="Загрузить">
</form>

{% if message %}
<div class="message">{{ message|safe }}</div>
{% endif %}
{% endblock %}